spring.datasource.url=jdbc:postgresql://ep-rough-cell-avg63xzo-pooler.c-11.us-east-1.aws.neon.tech:5432/neondb?user=neondb_owner&sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_YntBlZ5T3CiM

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect